### ISSUE TITLE
Should users be able to install this?  (setup.py)

### ISSUE THREAD

**Issue by hugadams** [blink1073/image_inspector#3]
I currently can't install these tools, but want to be able to use them in any python program.  It's easy enough to extend our PythonPATH, but is the a particular reason that this library shouldn't contain a setup.py file?  I'd be happy to submit a PR if this would be within the scope of the project.

**Comment by blink1073** [comment]
@hugadams, thanks for the nudge, good to go!

**Comment by hugadams** [comment]
Awesome man thanks!
